package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Armoire generated by hbm2java
 */
@Entity
@Table(name = "ARMOIRE")
public class Armoire implements java.io.Serializable {

	private long idarmoire;
	private Datacenter datacenter;
	private String nom;
	private String position;
	private Long numero;
	private String etat;
	private String type;
	private Long nombreunite;
	private String lieu;
	private Set<Equipementinformatique> equipementinformatiques = new HashSet<Equipementinformatique>(0);
	private Set<Equipementreseau> equipementreseaus = new HashSet<Equipementreseau>(0);
	private Set<Equipementelectrique> equipementelectriques = new HashSet<Equipementelectrique>(0);

	public Armoire() {
	}

	public Armoire(long idarmoire) {
		this.idarmoire = idarmoire;
	}

	public Armoire(long idarmoire, Datacenter datacenter, String nom, String position, Long numero, String etat,
			String type, Long nombreunite, String lieu, Set<Equipementinformatique> equipementinformatiques,
			Set<Equipementreseau> equipementreseaus, Set<Equipementelectrique> equipementelectriques) {
		this.idarmoire = idarmoire;
		this.datacenter = datacenter;
		this.nom = nom;
		this.position = position;
		this.numero = numero;
		this.etat = etat;
		this.type = type;
		this.nombreunite = nombreunite;
		this.lieu = lieu;
		this.equipementinformatiques = equipementinformatiques;
		this.equipementreseaus = equipementreseaus;
		this.equipementelectriques = equipementelectriques;
	}

	@Id

	@Column(name = "IDARMOIRE", unique = true, nullable = false, precision = 12, scale = 0)
	public long getIdarmoire() {
		return this.idarmoire;
	}

	public void setIdarmoire(long idarmoire) {
		this.idarmoire = idarmoire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDDATA")
	public Datacenter getDatacenter() {
		return this.datacenter;
	}

	public void setDatacenter(Datacenter datacenter) {
		this.datacenter = datacenter;
	}

	@Column(name = "NOM", length = 4000)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "POSITION", length = 4000)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "NUMERO", precision = 12, scale = 0)
	public Long getNumero() {
		return this.numero;
	}

	public void setNumero(Long numero) {
		this.numero = numero;
	}

	@Column(name = "ETAT", length = 4000)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "TYPE", length = 4000)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "NOMBREUNITE", precision = 12, scale = 0)
	public Long getNombreunite() {
		return this.nombreunite;
	}

	public void setNombreunite(Long nombreunite) {
		this.nombreunite = nombreunite;
	}

	@Column(name = "LIEU", length = 4000)
	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "armoire")
	public Set<Equipementinformatique> getEquipementinformatiques() {
		return this.equipementinformatiques;
	}

	public void setEquipementinformatiques(Set<Equipementinformatique> equipementinformatiques) {
		this.equipementinformatiques = equipementinformatiques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "armoire")
	public Set<Equipementreseau> getEquipementreseaus() {
		return this.equipementreseaus;
	}

	public void setEquipementreseaus(Set<Equipementreseau> equipementreseaus) {
		this.equipementreseaus = equipementreseaus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "armoire")
	public Set<Equipementelectrique> getEquipementelectriques() {
		return this.equipementelectriques;
	}

	public void setEquipementelectriques(Set<Equipementelectrique> equipementelectriques) {
		this.equipementelectriques = equipementelectriques;
	}

}
