package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Datacenter generated by hbm2java
 */
@Entity
@Table(name = "DATACENTER")
public class Datacenter implements java.io.Serializable {

	private long iddata;
	private String nom;
	private String type;
	private String ville;
	private String adresse;
	private String pays;
	private Set<Armoire> armoires = new HashSet<Armoire>(0);

	public Datacenter() {
	}

	public Datacenter(long iddata) {
		this.iddata = iddata;
	}

	public Datacenter(long iddata, String nom, String type, String ville, String adresse, String pays,
			Set<Armoire> armoires) {
		this.iddata = iddata;
		this.nom = nom;
		this.type = type;
		this.ville = ville;
		this.adresse = adresse;
		this.pays = pays;
		this.armoires = armoires;
	}

	@Id

	@Column(name = "IDDATA", unique = true, nullable = false, precision = 12, scale = 0)
	public long getIddata() {
		return this.iddata;
	}

	public void setIddata(long iddata) {
		this.iddata = iddata;
	}

	@Column(name = "NOM", length = 4000)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "TYPE", length = 4000)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "VILLE", length = 4000)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "ADRESSE", length = 4000)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "PAYS", length = 4000)
	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datacenter")
	public Set<Armoire> getArmoires() {
		return this.armoires;
	}

	public void setArmoires(Set<Armoire> armoires) {
		this.armoires = armoires;
	}

}
