package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dictionnaire generated by hbm2java
 */
@Entity
@Table(name = "DICTIONNAIRE")
public class Dictionnaire implements java.io.Serializable {

	private long iddictionnaire;
	private String pakagesnmp;
	private String description;
	private Set<Regle> regles = new HashSet<Regle>(0);

	public Dictionnaire() {
	}

	public Dictionnaire(long iddictionnaire) {
		this.iddictionnaire = iddictionnaire;
	}

	public Dictionnaire(long iddictionnaire, String pakagesnmp, String description, Set<Regle> regles) {
		this.iddictionnaire = iddictionnaire;
		this.pakagesnmp = pakagesnmp;
		this.description = description;
		this.regles = regles;
	}

	@Id

	@Column(name = "IDDICTIONNAIRE", unique = true, nullable = false, precision = 22, scale = 0)
	public long getIddictionnaire() {
		return this.iddictionnaire;
	}

	public void setIddictionnaire(long iddictionnaire) {
		this.iddictionnaire = iddictionnaire;
	}

	@Column(name = "PAKAGESNMP", length = 4000)
	public String getPakagesnmp() {
		return this.pakagesnmp;
	}

	public void setPakagesnmp(String pakagesnmp) {
		this.pakagesnmp = pakagesnmp;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dictionnaire")
	public Set<Regle> getRegles() {
		return this.regles;
	}

	public void setRegles(Set<Regle> regles) {
		this.regles = regles;
	}

}
