package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipementelectrique generated by hbm2java
 */
@Entity
@Table(name = "EQUIPEMENTELECTRIQUE")
public class Equipementelectrique implements java.io.Serializable {

	private long id;
	private Armoire armoire;
	private String type;
	private Long numerodeserie;
	private String modele;
	private String marque;
	private String ipadress;
	private String hostname;
	private String localisation;
	private String contact;
	private String etat;
	private Set<Periheralelec> periheralelecs = new HashSet<Periheralelec>(0);

	public Equipementelectrique() {
	}

	public Equipementelectrique(long id) {
		this.id = id;
	}

	public Equipementelectrique(long id, Armoire armoire, String type, Long numerodeserie, String modele, String marque,
			String ipadress, String hostname, String localisation, String contact, String etat,
			Set<Periheralelec> periheralelecs) {
		this.id = id;
		this.armoire = armoire;
		this.type = type;
		this.numerodeserie = numerodeserie;
		this.modele = modele;
		this.marque = marque;
		this.ipadress = ipadress;
		this.hostname = hostname;
		this.localisation = localisation;
		this.contact = contact;
		this.etat = etat;
		this.periheralelecs = periheralelecs;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDARMOIRE")
	public Armoire getArmoire() {
		return this.armoire;
	}

	public void setArmoire(Armoire armoire) {
		this.armoire = armoire;
	}

	@Column(name = "TYPE", length = 4000)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "NUMERODESERIE", precision = 12, scale = 0)
	public Long getNumerodeserie() {
		return this.numerodeserie;
	}

	public void setNumerodeserie(Long numerodeserie) {
		this.numerodeserie = numerodeserie;
	}

	@Column(name = "MODELE", length = 4000)
	public String getModele() {
		return this.modele;
	}

	public void setModele(String modele) {
		this.modele = modele;
	}

	@Column(name = "MARQUE", length = 4000)
	public String getMarque() {
		return this.marque;
	}

	public void setMarque(String marque) {
		this.marque = marque;
	}

	@Column(name = "IPADRESS", length = 4000)
	public String getIpadress() {
		return this.ipadress;
	}

	public void setIpadress(String ipadress) {
		this.ipadress = ipadress;
	}

	@Column(name = "HOSTNAME", length = 4000)
	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "LOCALISATION", length = 4000)
	public String getLocalisation() {
		return this.localisation;
	}

	public void setLocalisation(String localisation) {
		this.localisation = localisation;
	}

	@Column(name = "CONTACT", length = 4000)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "ETAT", length = 4000)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipementelectrique")
	public Set<Periheralelec> getPeriheralelecs() {
		return this.periheralelecs;
	}

	public void setPeriheralelecs(Set<Periheralelec> periheralelecs) {
		this.periheralelecs = periheralelecs;
	}

}
