package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "GROUPE")
public class Groupe implements java.io.Serializable {

	private long idg;
	private Privilege privilege;
	private String nom;
	private Set<Regle> regles = new HashSet<Regle>(0);
	private Set<Users> userses = new HashSet<Users>(0);

	public Groupe() {
	}

	public Groupe(long idg) {
		this.idg = idg;
	}

	public Groupe(long idg, Privilege privilege, String nom, Set<Regle> regles, Set<Users> userses) {
		this.idg = idg;
		this.privilege = privilege;
		this.nom = nom;
		this.regles = regles;
		this.userses = userses;
	}

	@Id

	@Column(name = "IDG", unique = true, nullable = false, precision = 12, scale = 0)
	public long getIdg() {
		return this.idg;
	}

	public void setIdg(long idg) {
		this.idg = idg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPRIVILEGE")
	public Privilege getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Privilege privilege) {
		this.privilege = privilege;
	}

	@Column(name = "NOM", length = 4000)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set<Regle> getRegles() {
		return this.regles;
	}

	public void setRegles(Set<Regle> regles) {
		this.regles = regles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
