package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historique generated by hbm2java
 */
@Entity
@Table(name = "HISTORIQUE")
public class Historique implements java.io.Serializable {

	private long id;
	private Users users;
	private String tacheeffect;
	private Date datedevisite;

	public Historique() {
	}

	public Historique(long id) {
		this.id = id;
	}

	public Historique(long id, Users users, String tacheeffect, Date datedevisite) {
		this.id = id;
		this.users = users;
		this.tacheeffect = tacheeffect;
		this.datedevisite = datedevisite;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSER")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "TACHEEFFECT", length = 4000)
	public String getTacheeffect() {
		return this.tacheeffect;
	}

	public void setTacheeffect(String tacheeffect) {
		this.tacheeffect = tacheeffect;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEVISITE", length = 7)
	public Date getDatedevisite() {
		return this.datedevisite;
	}

	public void setDatedevisite(Date datedevisite) {
		this.datedevisite = datedevisite;
	}

}
