package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Interfaceinf generated by hbm2java
 */
@Entity
@Table(name = "INTERFACEINF")
public class Interfaceinf implements java.io.Serializable {

	private long id;
	private long idperipheral;
	private String name;
	private String description;
	private long type;
	private String state;

	public Interfaceinf() {
	}

	public Interfaceinf(long id) {
		this.id = id;
	}

	public Interfaceinf(long id, long idperipheral, String name, String description, long type,
			String state) {
		this.id = id;
		this.idperipheral = idperipheral;
		this.name = name;
		this.description = description;
		this.type = type;
		this.state = state;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "IDPERIPHERAL", precision = 22, scale = 0)
	public long getIdperipheral() {
		return this.idperipheral;
	}

	public void setIdperipheral(long idperipheral) {
		this.idperipheral = idperipheral;
	}

	@Column(name = "NAME", length = 4000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TYPE", precision = 22, scale = 0)
	public long getType() {
		return this.type;
	}

	public void setType(long type) {
		this.type = type;
	}

	@Column(name = "STATE", length = 4000)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
