package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Peripheralinfo generated by hbm2java
 */
@Entity
@Table(name = "PERIPHERALINFO")
public class Peripheralinfo implements java.io.Serializable {

	private long idpripheral;
	private Equipementinformatique equipementinformatique;
	private long idequip;
	private String description;
	private String oid;
	private String uptime;
	private long nbport;

	public Peripheralinfo() {
	}

	public Peripheralinfo(long idpripheral) {
		this.idpripheral = idpripheral;
	}

	public Peripheralinfo(long idpripheral, Equipementinformatique equipementinformatique, long idequip,
			String description, String oid, String uptime, long nbport) {
		this.idpripheral = idpripheral;
		this.equipementinformatique = equipementinformatique;
		this.idequip = idequip;
		this.description = description;
		this.oid = oid;
		this.uptime = uptime;
		this.nbport = nbport;
	}

	@Id

	@Column(name = "IDPRIPHERAL", unique = true, nullable = false, precision = 22, scale = 0)
	public long getIdpripheral() {
		return this.idpripheral;
	}

	public void setIdpripheral(long idpripheral) {
		this.idpripheral = idpripheral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID")
	public Equipementinformatique getEquipementinformatique() {
		return this.equipementinformatique;
	}

	public void setEquipementinformatique(Equipementinformatique equipementinformatique) {
		this.equipementinformatique = equipementinformatique;
	}

	@Column(name = "IDEQUIP", precision = 22, scale = 0)
	public long getIdequip() {
		return this.idequip;
	}

	public void setIdequip(long idequip) {
		this.idequip = idequip;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "OID", length = 4000)
	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	@Column(name = "UPTIME", length = 4000)
	public String getUptime() {
		return this.uptime;
	}

	public void setUptime(String uptime) {
		this.uptime = uptime;
	}

	@Column(name = "NBPORT", precision = 22, scale = 0)
	public long getNbport() {
		return this.nbport;
	}

	public void setNbport(long nbport) {
		this.nbport = nbport;
	}

}
