package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Peripheralres generated by hbm2java
 */
@Entity
@Table(name = "PERIPHERALRES")
public class Peripheralres implements java.io.Serializable {

	private long idpripheral;
	private Equipementreseau equipementreseau;
	private long idequi;
	private String description;
	private String oid;
	private long uptime;
	private long nbport;

	public Peripheralres() {
	}

	public Peripheralres(long idpripheral) {
		this.idpripheral = idpripheral;
	}

	public Peripheralres(long idpripheral, Equipementreseau equipementreseau, long idequi,
			String description, String oid, long uptime, long nbport) {
		this.idpripheral = idpripheral;
		this.equipementreseau = equipementreseau;
		this.idequi = idequi;
		this.description = description;
		this.oid = oid;
		this.uptime = uptime;
		this.nbport = nbport;
	}

	@Id

	@Column(name = "IDPRIPHERAL", unique = true, nullable = false, precision = 22, scale = 0)
	public long getIdpripheral() {
		return this.idpripheral;
	}

	public void setIdpripheral(long idpripheral) {
		this.idpripheral = idpripheral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID")
	public Equipementreseau getEquipementreseau() {
		return this.equipementreseau;
	}

	public void setEquipementreseau(Equipementreseau equipementreseau) {
		this.equipementreseau = equipementreseau;
	}

	@Column(name = "IDEQUI", precision = 22, scale = 0)
	public long getIdequi() {
		return this.idequi;
	}

	public void setIdequi(long idequi) {
		this.idequi = idequi;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "OID", length = 4000)
	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	@Column(name = "UPTIME", precision = 22, scale = 0)
	public long getUptime() {
		return this.uptime;
	}

	public void setUptime(long uptime) {
		this.uptime = uptime;
	}

	@Column(name = "NBPORT", precision = 22, scale = 0)
	public long getNbport() {
		return this.nbport;
	}

	public void setNbport(long nbport) {
		this.nbport = nbport;
	}

}
