package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name = "PRIVILEGE")
public class Privilege implements java.io.Serializable {

	private long idprivilege;
	private String nom;
	private String accessprivilege;
	private Set<Groupe> groupes = new HashSet<Groupe>(0);

	public Privilege() {
	}

	public Privilege(long idprivilege) {
		this.idprivilege = idprivilege;
	}

	public Privilege(long idprivilege, String nom, String accessprivilege, Set<Groupe> groupes) {
		this.idprivilege = idprivilege;
		this.nom = nom;
		this.accessprivilege = accessprivilege;
		this.groupes = groupes;
	}

	@Id

	@Column(name = "IDPRIVILEGE", unique = true, nullable = false, precision = 22, scale = 0)
	public long getIdprivilege() {
		return this.idprivilege;
	}

	public void setIdprivilege(long idprivilege) {
		this.idprivilege = idprivilege;
	}

	@Column(name = "NOM", length = 4000)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "ACCESSPRIVILEGE", length = 4000)
	public String getAccessprivilege() {
		return this.accessprivilege;
	}

	public void setAccessprivilege(String accessprivilege) {
		this.accessprivilege = accessprivilege;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "privilege")
	public Set<Groupe> getGroupes() {
		return this.groupes;
	}

	public void setGroupes(Set<Groupe> groupes) {
		this.groupes = groupes;
	}

}
