package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Regle generated by hbm2java
 */
@Entity
@Table(name = "REGLE")
public class Regle implements java.io.Serializable {

	private long id;
	private Dictionnaire dictionnaire;
	private Groupe groupe;
	private String nom;

	public Regle() {
	}

	public Regle(long id) {
		this.id = id;
	}

	public Regle(long id, Dictionnaire dictionnaire, Groupe groupe, String nom) {
		this.id = id;
		this.dictionnaire = dictionnaire;
		this.groupe = groupe;
		this.nom = nom;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDDICTIONNAIRE")
	public Dictionnaire getDictionnaire() {
		return this.dictionnaire;
	}

	public void setDictionnaire(Dictionnaire dictionnaire) {
		this.dictionnaire = dictionnaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDG")
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	@Column(name = "NOM", length = 4000)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
