package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ALI generated by hbm2java
 */
@Entity
@Table(name = "ALI")
public class ALI implements java.io.Serializable {

	private long isSab;
	private String nomSab;

	public ALI() {
	}

	public ALI(long isSab) {
		this.isSab = isSab;
	}

	public ALI(long isSab, String nomSab) {
		this.isSab = isSab;
		this.nomSab = nomSab;
	}

	@Id

	@Column(name = "IS_SAB", unique = true, nullable = false, precision = 22, scale = 0)
	public long getIsSab() {
		return this.isSab;
	}

	public void setIsSab(long isSab) {
		this.isSab = isSab;
	}

	@Column(name = "NOM_SAB", length = 4000)
	public String getNomSab() {
		return this.nomSab;
	}

	public void setNomSab(String nomSab) {
		this.nomSab = nomSab;
	}

}
