package com.aattijari.bank.entity;
// Generated 26 mai 2016 20:25:06 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS")
public class Users implements java.io.Serializable {

	private long id;
	private Groupe groupe;
	private String username;
	private String prenom;
	private long tel;
	private String email;
	private String fonction;
	private long matricule;
	private String password;
	private long enabled;
	private Set<Historique> historiques = new HashSet<Historique>(0);

	public Users() {
	}

	public Users(long id) {
		this.id = id;
	}

	public Users(long id, Groupe groupe, String username, String prenom, long tel, String email,
			String fonction, long matricule, String password, long enabled, Set<Historique> historiques) {
		this.id = id;
		this.groupe = groupe;
		this.username = username;
		this.prenom = prenom;
		this.tel = tel;
		this.email = email;
		this.fonction = fonction;
		this.matricule = matricule;
		this.password = password;
		this.enabled = enabled;
		this.historiques = historiques;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDG")
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	@Column(name = "USERNAME", length = 4000)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PRENOM", length = 4000)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "TEL", precision = 22, scale = 0)
	public long getTel() {
		return this.tel;
	}

	public void setTel(long tel) {
		this.tel = tel;
	}

	@Column(name = "EMAIL", length = 4000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "FONCTION", length = 4000)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	@Column(name = "MATRICULE", precision = 22, scale = 0)
	public long getMatricule() {
		return this.matricule;
	}

	public void setMatricule(long matricule) {
		this.matricule = matricule;
	}

	@Column(name = "PASSWORD", length = 4000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ENABLED", precision = 22, scale = 0)
	public long getEnabled() {
		return this.enabled;
	}

	public void setEnabled(long enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Historique> getHistoriques() {
		return this.historiques;
	}

	public void setHistoriques(Set<Historique> historiques) {
		this.historiques = historiques;
	}

}
